export const inquiriesCopy = {
  en: {
    title: "Inquiries CRM",
    subtitle:
      "Operational list/detail for lead follow-up, assignment, notes timeline, and contact quick actions.",
    loginTitle: "Admin sign in",
    loginSubtitle: "Use the same admin credentials as /api/v1/auth/login.",
    sessionActive: "Signed in session",
    sessionAs: "Signed in as",
    sessionUnknown: "Signed in (email unavailable)",
    sessionHint: "Keep this session active to reload the queue, export CSV, and save shared follow-up presets.",
    sessionRole: "Active role",
    sessionCoverage: "Control scope",
    sessionCoverageValue: "Filters, exports, saved presets, and follow-up updates",
    email: "Admin email",
    password: "Password",
    signIn: "Sign in",
    signingIn: "Signing in",
    signOut: "Sign out",
    loginMissing: "Email and password are required.",
    loginInvalid: "Invalid credentials.",
    loginError: "Unable to sign in right now.",
    loading: "Loading inquiries",
    reload: "Reload",
    exportCsv: "Export CSV",
    empty: "No inquiries match current filters.",
    error: "Unable to load CRM data right now.",
    authRequired: "Sign in to load admin CRM data.",
    filters: "Filters",
    filtersDescription: "Refine the active queue, save presets, or reload the latest lead list without leaving this workspace.",
    status: "Status",
    source: "Source",
    purpose: "Purpose",
    dateFrom: "Date from",
    dateTo: "Date to",
    followUp: "Follow-up status",
    search: "Search",
    searchPlaceholder: "Search name, source, purpose, or contact",
    clear: "Clear",
    apply: "Apply filters",
    tableView: "Table view",
    kanbanView: "Kanban view",
    saveFilter: "Save filter",
    saveAs: "Save as",
    savedFilters: "Saved filters",
    savedFiltersHint: "Store the current filter mix as an operator preset, then load it back in one click.",
    savedFiltersEmpty: "No saved presets yet for this role.",
    loadFilter: "Load filter",
    roleScope: "Role scope",
    moveStatusError: "Unable to move inquiry status.",
    list: "Inquiries",
    listDescription: "Review active inquiries in table or kanban view, then open one item for follow-up details.",
    emptyHint: "Adjust filters or reload the queue to fetch the latest leads.",
    loadingHint: "Refreshing the current inquiry queue and filters.",
    loadingDetails: "Loading inquiry details",
    movingStatus: "Updating inquiry status",
    total: "Total",
    details: "Details",
    detailsDescription: "Selected inquiry context, contact routes, follow-up controls, and timeline in one operator panel.",
    timeline: "Timeline",
    timelineDescription: "Recent actions and notes for the selected inquiry.",
    timelineEmpty: "No timeline events recorded yet.",
    contactActions: "Contact actions",
    contactActionsDescription: "Open the fastest available contact path for this inquiry.",
    contactActionsEmpty: "No direct contact actions are available for this inquiry yet.",
    whatsapp: "WhatsApp",
    phone: "Phone",
    emailAction: "Email",
    noDetails: "Select an inquiry from the list to view full details and timeline.",
    saveFollowUp: "Save follow-up",
    saving: "Saving follow-up",
    followUpDescription: "Update owner follow-up status and next due time for the selected inquiry.",
    followUpSaved: "Follow-up updated.",
    followUpDueAt: "Follow-up due at",
    spam: "Spam",
    duplicate: "Duplicate",
    sourcePage: "Source page",
    createdAt: "Created at",
    intent: "Purpose/Intent",
    loadTimelineError: "Unable to load timeline.",
    saveFollowUpError: "Unable to update follow-up.",
  },
  th: {
    title: "จัดการอินไควรี",
    subtitle:
      "พื้นที่งาน CRM สำหรับติดตามลีดแบบใช้งานจริง ครบทั้งรายการ รายละเอียด ไทม์ไลน์ และช่องทางติดต่อด่วน",
    loginTitle: "เข้าสู่ระบบแอดมิน",
    loginSubtitle: "ใช้บัญชีแอดมินเดียวกับเส้นทาง /api/v1/auth/login",
    sessionActive: "เซสชันที่เข้าสู่ระบบอยู่",
    sessionAs: "เข้าสู่ระบบเป็น",
    sessionUnknown: "เข้าสู่ระบบแล้ว (ไม่พบอีเมล)",
    sessionHint: "คงเซสชันนี้ไว้เพื่อโหลดคิวใหม่ ส่งออก CSV และบันทึกชุดตัวกรองสำหรับงานติดตามได้ทันที",
    sessionRole: "สิทธิ์ที่ใช้งานอยู่",
    sessionCoverage: "ขอบเขตงานที่ควบคุมได้",
    sessionCoverageValue: "ตัวกรอง การส่งออก ชุดตัวกรองที่บันทึกไว้ และการอัปเดตสถานะติดตาม",
    email: "อีเมลแอดมิน",
    password: "รหัสผ่าน",
    signIn: "เข้าสู่ระบบ",
    signingIn: "กำลังเข้าสู่ระบบ",
    signOut: "ออกจากระบบ",
    loginMissing: "ต้องกรอกอีเมลและรหัสผ่าน",
    loginInvalid: "ข้อมูลเข้าสู่ระบบไม่ถูกต้อง",
    loginError: "ไม่สามารถเข้าสู่ระบบได้ในขณะนี้",
    loading: "กำลังโหลดรายการ",
    reload: "โหลดใหม่",
    exportCsv: "ส่งออก CSV",
    empty: "ไม่พบรายการตามตัวกรองปัจจุบัน",
    error: "ไม่สามารถโหลดข้อมูล CRM ได้ในขณะนี้",
    authRequired: "กรุณาเข้าสู่ระบบก่อนใช้งาน CRM หลังบ้าน",
    filters: "ตัวกรอง",
    filtersDescription: "ปรับคิวงานที่กำลังดู บันทึกชุดตัวกรอง และโหลดรายการลีดล่าสุดได้จากพื้นที่นี้โดยไม่ต้องออกหน้า",
    status: "สถานะ",
    source: "ที่มา",
    purpose: "วัตถุประสงค์",
    dateFrom: "วันที่เริ่ม",
    dateTo: "วันที่สิ้นสุด",
    followUp: "สถานะติดตาม",
    search: "ค้นหา",
    searchPlaceholder: "ค้นหาชื่อ ที่มา วัตถุประสงค์ หรือข้อมูลติดต่อ",
    clear: "ล้างค่า",
    apply: "ใช้ตัวกรอง",
    tableView: "มุมมองตาราง",
    kanbanView: "มุมมองคัมบัน",
    saveFilter: "บันทึกตัวกรอง",
    saveAs: "บันทึกเป็น",
    savedFilters: "ตัวกรองที่บันทึกไว้",
    savedFiltersHint: "เก็บชุดตัวกรองปัจจุบันไว้เป็นค่าที่ใช้บ่อย แล้วเรียกกลับมาใช้ได้ทันทีในคลิกเดียว",
    savedFiltersEmpty: "ยังไม่มีชุดตัวกรองที่บันทึกไว้สำหรับสิทธิ์นี้",
    loadFilter: "เรียกชุดตัวกรอง",
    roleScope: "ขอบเขตตามสิทธิ์",
    moveStatusError: "ย้ายสถานะรายการไม่สำเร็จ",
    list: "รายการอินไควรี",
    listDescription: "ดูรายการอินไควรีแบบตารางหรือคัมบัน แล้วเลือกแต่ละรายการเพื่อทำงานติดตามต่อ",
    emptyHint: "ลองปรับตัวกรองหรือโหลดคิวใหม่เพื่อดึงรายการล่าสุด",
    loadingHint: "กำลังรีเฟรชคิวอินไควรีตามตัวกรองปัจจุบัน",
    loadingDetails: "กำลังโหลดรายละเอียดรายการ",
    movingStatus: "กำลังอัปเดตสถานะรายการ",
    total: "ทั้งหมด",
    details: "รายละเอียด",
    detailsDescription: "สรุปบริบทของรายการที่เลือก ช่องทางติดต่อ การติดตาม และไทม์ไลน์ไว้ในแผงเดียว",
    timeline: "ไทม์ไลน์",
    timelineDescription: "ลำดับเหตุการณ์และบันทึกล่าสุดของอินไควรีที่เลือก",
    timelineEmpty: "ยังไม่มีเหตุการณ์ในไทม์ไลน์",
    contactActions: "ช่องทางติดต่อด่วน",
    contactActionsDescription: "เปิดช่องทางติดต่อที่พร้อมใช้งานได้ทันทีจากรายการนี้",
    contactActionsEmpty: "ยังไม่มีช่องทางติดต่อโดยตรงสำหรับรายการนี้",
    whatsapp: "WhatsApp",
    phone: "โทร",
    emailAction: "อีเมล",
    noDetails: "เลือกรายการจากฝั่งซ้ายเพื่อดูรายละเอียดและไทม์ไลน์",
    saveFollowUp: "บันทึกสถานะติดตาม",
    saving: "กำลังบันทึก",
    followUpDescription: "อัปเดตสถานะติดตามและเวลานัดหมายครั้งถัดไปของรายการที่เลือก",
    followUpSaved: "บันทึกสถานะติดตามแล้ว",
    followUpDueAt: "กำหนดติดตาม",
    spam: "สแปม",
    duplicate: "ซ้ำ",
    sourcePage: "หน้าต้นทาง",
    createdAt: "เวลาสร้าง",
    intent: "วัตถุประสงค์",
    loadTimelineError: "โหลดไทม์ไลน์ไม่สำเร็จ",
    saveFollowUpError: "อัปเดตสถานะติดตามไม่สำเร็จ",
  },
} as const;

export type InquiryCopy = (typeof inquiriesCopy)[keyof typeof inquiriesCopy];
