export const inquiriesCopy = {
  en: {
    title: "Lead Inbox",
    subtitle:
      "Find the right lead fast, set the next action, and keep the queue moving without changing the backend workflow.",
    loginTitle: "Admin sign in",
    loginSubtitle: "Use the same admin credentials as /api/v1/auth/login.",
    sessionActive: "Signed in session",
    sessionAs: "Signed in as",
    sessionUnknown: "Signed in (email unavailable)",
    sessionHint: "Keep this session active to reload the queue, export CSV, and save shared follow-up presets.",
    sessionRole: "Active role",
    sessionCoverage: "Inbox tools",
    sessionCoverageValue: "Filters, exports, saved presets, and follow-up updates",
    email: "Admin email",
    password: "Password",
    signIn: "Sign in",
    signingIn: "Signing in",
    signOut: "Sign out",
    loginMissing: "Email and password are required.",
    loginInvalid: "Invalid credentials.",
    loginError: "Unable to sign in right now.",
    loading: "Loading inquiries",
    reload: "Reload",
    exportCsv: "Export CSV",
    empty: "No inquiries match current filters.",
    error: "Unable to load CRM data right now.",
    authRequired: "Sign in to load admin CRM data.",
    filters: "Filters",
    filtersDescription: "Refine the active queue, save views, and reload the latest leads without leaving the inbox.",
    filterStateDraft: "Draft filters are not applied yet. Apply filters to refresh the visible queue.",
    filterStateApplied: "Queue is synced with the current filters. Reload and Export CSV use the visible queue.",
    filterScopeDefault: "Current queue uses the default filter set.",
    filterScopeFiltered: "Current queue uses a filtered result set.",
    currentDraft: "Current draft",
    currentDraftDefault: "No draft filters yet",
    appliedQueue: "Applied queue",
    appliedQueueDefault: "Default filters",
    draftChangesPending: "Draft changes pending",
    removeFilter: "Remove filter",
    status: "Status",
    source: "Source",
    purpose: "Purpose",
    dateFrom: "Date from",
    dateTo: "Date to",
    followUp: "Follow-up status",
    search: "Search",
    searchPlaceholder: "Search name, source, purpose, or contact",
    clear: "Clear",
    apply: "Apply filters",
    tableView: "Inbox",
    kanbanView: "Pipeline",
    saveFilter: "Save view",
    saveAs: "Save current view",
    savedFilters: "Saved views",
    savedFiltersHint: "Store the current filter mix as a reusable inbox view, then load it back in one click.",
    savedFiltersEmpty: "No saved presets yet for this role.",
    loadFilter: "Load view",
    roleScope: "View scope",
    close: "Close",
    moveStatusError: "Unable to move inquiry status.",
    moveStatusUpdated: "Inquiry status updated.",
    list: "Lead queue",
    listDescription: "Scan the queue, choose the right lead, and open detail context without leaving the inbox.",
    rowActionHint: "Open a lead to review the snapshot, set the next action, and then use contact options if needed.",
    rowActions: "Next steps",
    noRowActions: "No direct contact route",
    openDetails: "Open details",
    viewingDetails: "Viewing details",
    emptyHint: "Adjust filters or reload the queue to fetch the latest leads.",
    loadingHint: "Refreshing the current inquiry queue and filters.",
    loadingDetails: "Loading inquiry details",
    movingStatus: "Updating inquiry status",
    total: "Total",
    details: "Lead detail",
    detailsDescription: "Lead snapshot, next action, contact routes, and timeline in one focused workspace.",
    detailSnapshotTitle: "Lead snapshot",
    detailSnapshotDescription: "Review the selected lead profile first, then move straight into contact and follow-up actions.",
    detailActionsTitle: "Next action",
    detailActionsDescription: "Set follow-up status and due time first so the queue always reflects the real next step.",
    detailContextTitle: "Context & timeline",
    detailContextDescription: "Use guidance and recent activity after the next action is already set.",
    advisorAssist: "Advisor assist",
    advisorAssistDescription: "Instant response copy, recommended approach, first reply, and follow-up sequence derived from the lead context.",
    timeline: "Timeline",
    timelineDescription: "Recent actions and notes for the selected inquiry.",
    timelineEmpty: "No timeline events recorded yet.",
    contactActions: "Contact actions",
    contactActionsDescription: "Open the fastest available contact path for this inquiry.",
    contactActionsEmpty: "No direct contact actions are available for this inquiry yet.",
    whatsapp: "WhatsApp",
    phone: "Phone",
    emailAction: "Email",
    noDetails: "Select an inquiry from the list to view full details and timeline.",
    emptyDetails: "No inquiries match current filters. Adjust filters or reload the queue to fetch the latest leads.",
    saveFollowUp: "Save next action",
    saving: "Saving next action",
    followUpDescription: "Update the follow-up status and due time for the selected lead.",
    followUpActionHint: "Save this next action after adjusting status or due time so the inbox stays current.",
    followUpSaved: "Next action updated.",
    followUpDueAt: "Follow-up due at",
    spam: "Spam",
    duplicate: "Duplicate",
    sourcePage: "Source page",
    createdAt: "Created at",
    intent: "Purpose/Intent",
    projectsInScope: "Projects in scope",
    buyerFit: "Buyer fit",
    signalLevel: "Signal level",
    routeHint: "Routing hint",
    responseChannel: "Response channel",
    priorityLabel: "Priority",
    instantResponse: "Instant response",
    recommendedApproach: "Recommended approach",
    suggestedFirstReply: "Suggested first reply",
    followUpPlan: "Follow-up plan",
    stopConditions: "Stop conditions",
    loadTimelineError: "Unable to load timeline.",
    saveFollowUpError: "Unable to update follow-up.",
  },
  th: {
    title: "Lead Inbox",
    subtitle:
      "หา lead ที่ต้องจัดการให้เร็ว ตั้ง next action แล้วเดินคิวงานต่อได้ทันที โดยไม่เปลี่ยน backend workflow เดิม",
    loginTitle: "เข้าสู่ระบบแอดมิน",
    loginSubtitle: "ใช้บัญชีแอดมินเดียวกับเส้นทาง /api/v1/auth/login",
    sessionActive: "เซสชันที่เข้าสู่ระบบอยู่",
    sessionAs: "เข้าสู่ระบบเป็น",
    sessionUnknown: "เข้าสู่ระบบแล้ว (ไม่พบอีเมล)",
    sessionHint: "คงเซสชันนี้ไว้เพื่อโหลดคิวใหม่ ส่งออก CSV และบันทึกชุดตัวกรองสำหรับงานติดตามได้ทันที",
    sessionRole: "สิทธิ์ที่ใช้งานอยู่",
    sessionCoverage: "เครื่องมือของ inbox",
    sessionCoverageValue: "ตัวกรอง การส่งออก ชุดตัวกรองที่บันทึกไว้ และการอัปเดตสถานะติดตาม",
    email: "อีเมลแอดมิน",
    password: "รหัสผ่าน",
    signIn: "เข้าสู่ระบบ",
    signingIn: "กำลังเข้าสู่ระบบ",
    signOut: "ออกจากระบบ",
    loginMissing: "ต้องกรอกอีเมลและรหัสผ่าน",
    loginInvalid: "ข้อมูลเข้าสู่ระบบไม่ถูกต้อง",
    loginError: "ไม่สามารถเข้าสู่ระบบได้ในขณะนี้",
    loading: "กำลังโหลดรายการ",
    reload: "โหลดใหม่",
    exportCsv: "ส่งออก CSV",
    empty: "ไม่พบรายการตามตัวกรองปัจจุบัน",
    error: "ไม่สามารถโหลดข้อมูล CRM ได้ในขณะนี้",
    authRequired: "กรุณาเข้าสู่ระบบก่อนใช้งาน CRM หลังบ้าน",
    filters: "ตัวกรอง",
    filtersDescription: "ปรับคิวที่กำลังดู บันทึกมุมมองที่ใช้บ่อย และโหลดลีดล่าสุดได้จากหน้าเดียว",
    filterStateDraft: "ตัวกรองที่แก้ไขไว้ยังไม่ถูกใช้กับคิวปัจจุบัน กดใช้ตัวกรองเพื่อรีเฟรชรายการที่มองเห็นอยู่",
    filterStateApplied: "คิวปัจจุบันตรงกับตัวกรองที่ใช้งานอยู่แล้ว ปุ่มโหลดใหม่และส่งออก CSV จะอ้างอิงคิวที่มองเห็นอยู่",
    filterScopeDefault: "คิวปัจจุบันใช้ชุดตัวกรองเริ่มต้น",
    filterScopeFiltered: "คิวปัจจุบันใช้ผลลัพธ์ที่ผ่านการกรองแล้ว",
    currentDraft: "ฉบับร่างปัจจุบัน",
    currentDraftDefault: "ยังไม่มีตัวกรองฉบับร่าง",
    appliedQueue: "คิวที่ใช้งานอยู่",
    appliedQueueDefault: "ตัวกรองเริ่มต้น",
    draftChangesPending: "มีตัวกรองฉบับรอใช้",
    removeFilter: "ลบตัวกรอง",
    status: "สถานะ",
    source: "ที่มา",
    purpose: "วัตถุประสงค์",
    dateFrom: "วันที่เริ่ม",
    dateTo: "วันที่สิ้นสุด",
    followUp: "สถานะติดตาม",
    search: "ค้นหา",
    searchPlaceholder: "ค้นหาชื่อ ที่มา วัตถุประสงค์ หรือข้อมูลติดต่อ",
    clear: "ล้างค่า",
    apply: "ใช้ตัวกรอง",
    tableView: "Inbox",
    kanbanView: "Pipeline",
    saveFilter: "บันทึกมุมมอง",
    saveAs: "บันทึกมุมมองนี้",
    savedFilters: "มุมมองที่บันทึกไว้",
    savedFiltersHint: "เก็บชุดตัวกรองปัจจุบันไว้เป็นมุมมองของ inbox แล้วเรียกกลับมาใช้ได้ทันทีในคลิกเดียว",
    savedFiltersEmpty: "ยังไม่มีชุดตัวกรองที่บันทึกไว้สำหรับสิทธิ์นี้",
    loadFilter: "เรียกมุมมอง",
    roleScope: "ขอบเขตของมุมมอง",
    close: "ปิด",
    moveStatusError: "ย้ายสถานะรายการไม่สำเร็จ",
    moveStatusUpdated: "อัปเดตสถานะรายการแล้ว",
    list: "คิวลีด",
    listDescription: "สแกนคิว เลือก lead ที่ใช่ แล้วเปิดรายละเอียดต่อได้ทันทีจากหน้าเดียว",
    rowActionHint: "เปิด lead เพื่อดู snapshot ตั้ง next action แล้วค่อยใช้ช่องทางติดต่อเมื่อจำเป็น",
    rowActions: "ขั้นตอนถัดไป",
    noRowActions: "ยังไม่มีช่องทางติดต่อด่วน",
    openDetails: "เปิดรายละเอียด",
    viewingDetails: "กำลังดูรายละเอียด",
    emptyHint: "ลองปรับตัวกรองหรือโหลดคิวใหม่เพื่อดึงรายการล่าสุด",
    loadingHint: "กำลังรีเฟรชคิวอินไควรีตามตัวกรองปัจจุบัน",
    loadingDetails: "กำลังโหลดรายละเอียดรายการ",
    movingStatus: "กำลังอัปเดตสถานะรายการ",
    total: "ทั้งหมด",
    details: "รายละเอียด lead",
    detailsDescription: "รวม lead snapshot, next action, ช่องทางติดต่อ และ timeline ไว้ใน workspace เดียว",
    detailSnapshotTitle: "สรุปข้อมูลลีด",
    detailSnapshotDescription: "ตรวจข้อมูลหลักของลีดก่อน แล้วค่อยไปยังช่องทางติดต่อและการติดตามที่ต้องทำทันที",
    detailActionsTitle: "งานถัดไป",
    detailActionsDescription: "ตั้งสถานะติดตามและกำหนดเวลาถัดไปก่อน เพื่อให้คิวสะท้อนงานจริงเสมอ",
    detailContextTitle: "บริบทและไทม์ไลน์",
    detailContextDescription: "ใช้อ่านคำแนะนำและกิจกรรมล่าสุดหลังจากตั้งงานถัดไปเรียบร้อยแล้ว",
    advisorAssist: "ตัวช่วยสำหรับ advisor",
    advisorAssistDescription: "สรุปข้อความตอบกลับทันที แนวทางคุยต่อ ข้อความตอบครั้งแรก และลำดับ follow-up ที่ derive มาจากบริบท lead",
    timeline: "ไทม์ไลน์",
    timelineDescription: "ลำดับเหตุการณ์และบันทึกล่าสุดของอินไควรีที่เลือก",
    timelineEmpty: "ยังไม่มีเหตุการณ์ในไทม์ไลน์",
    contactActions: "ช่องทางติดต่อด่วน",
    contactActionsDescription: "เปิดช่องทางติดต่อที่พร้อมใช้งานได้ทันทีจากรายการนี้",
    contactActionsEmpty: "ยังไม่มีช่องทางติดต่อโดยตรงสำหรับรายการนี้",
    whatsapp: "WhatsApp",
    phone: "โทร",
    emailAction: "อีเมล",
    noDetails: "เลือกรายการจากฝั่งซ้ายเพื่อดูรายละเอียดและไทม์ไลน์",
    emptyDetails: "ไม่พบรายการตามตัวกรองปัจจุบัน ลองปรับตัวกรองหรือโหลดคิวใหม่เพื่อดึงรายการล่าสุด",
    saveFollowUp: "บันทึกงานถัดไป",
    saving: "กำลังบันทึกงานถัดไป",
    followUpDescription: "อัปเดตสถานะติดตามและเวลางานถัดไปของลีดที่เลือก",
    followUpActionHint: "บันทึกงานถัดไปหลังจากปรับสถานะหรือเวลา เพื่อให้ inbox ตรงกับงานจริง",
    followUpSaved: "อัปเดตงานถัดไปแล้ว",
    followUpDueAt: "กำหนดติดตาม",
    spam: "สแปม",
    duplicate: "ซ้ำ",
    sourcePage: "หน้าต้นทาง",
    createdAt: "เวลาสร้าง",
    intent: "วัตถุประสงค์",
    projectsInScope: "โครงการในบริบทนี้",
    buyerFit: "ลักษณะผู้ซื้อที่เหมาะ",
    signalLevel: "ระดับสัญญาณ",
    routeHint: "แนวทาง routing",
    responseChannel: "ช่องทางตอบกลับ",
    priorityLabel: "ความสำคัญ",
    instantResponse: "ข้อความตอบกลับทันที",
    recommendedApproach: "แนวทางคุยต่อที่แนะนำ",
    suggestedFirstReply: "ข้อความเปิดบทสนทนาที่แนะนำ",
    followUpPlan: "แผน follow-up",
    stopConditions: "เงื่อนไขหยุด follow-up",
    loadTimelineError: "โหลดไทม์ไลน์ไม่สำเร็จ",
    saveFollowUpError: "อัปเดตสถานะติดตามไม่สำเร็จ",
  },
} as const;

export type InquiryCopy = (typeof inquiriesCopy)[keyof typeof inquiriesCopy];
