import type { Config } from 'tailwindcss';

const config: Config = {
  content: ['./app/**/*.{js,ts,jsx,tsx}', './components/**/*.{js,ts,jsx,tsx}', './lib/**/*.{js,ts,jsx,tsx}'],
  theme: {
    extend: {
      colors: {
        admin: {
          primary: {
            50: 'var(--admin-color-primary-50)',
            100: 'var(--admin-color-primary-100)',
            200: 'var(--admin-color-primary-200)',
            300: 'var(--admin-color-primary-300)',
            400: 'var(--admin-color-primary-400)',
            500: 'var(--admin-color-primary-500)',
            600: 'var(--admin-color-primary-600)',
            700: 'var(--admin-color-primary-700)',
            800: 'var(--admin-color-primary-800)',
            900: 'var(--admin-color-primary-900)',
          },
          neutral: {
            0: 'var(--admin-color-neutral-0)',
            25: 'var(--admin-color-neutral-25)',
            50: 'var(--admin-color-neutral-50)',
            100: 'var(--admin-color-neutral-100)',
            150: 'var(--admin-color-neutral-150)',
            200: 'var(--admin-color-neutral-200)',
            300: 'var(--admin-color-neutral-300)',
            400: 'var(--admin-color-neutral-400)',
            500: 'var(--admin-color-neutral-500)',
            600: 'var(--admin-color-neutral-600)',
            700: 'var(--admin-color-neutral-700)',
            800: 'var(--admin-color-neutral-800)',
            900: 'var(--admin-color-neutral-900)',
          },
          success: {
            50: 'var(--admin-color-success-50)',
            100: 'var(--admin-color-success-100)',
            500: 'var(--admin-color-success-500)',
            600: 'var(--admin-color-success-600)',
            700: 'var(--admin-color-success-700)',
          },
          warning: {
            50: 'var(--admin-color-warning-50)',
            100: 'var(--admin-color-warning-100)',
            500: 'var(--admin-color-warning-500)',
            600: 'var(--admin-color-warning-600)',
            700: 'var(--admin-color-warning-700)',
          },
          danger: {
            50: 'var(--admin-color-danger-50)',
            100: 'var(--admin-color-danger-100)',
            500: 'var(--admin-color-danger-500)',
            600: 'var(--admin-color-danger-600)',
            700: 'var(--admin-color-danger-700)',
          },
          info: {
            50: 'var(--admin-color-info-50)',
            100: 'var(--admin-color-info-100)',
            500: 'var(--admin-color-info-500)',
            600: 'var(--admin-color-info-600)',
            700: 'var(--admin-color-info-700)',
          },
          bg: {
            canvas: 'var(--admin-bg-canvas)',
            sidebar: 'var(--admin-bg-sidebar)',
            header: 'var(--admin-bg-header)',
            card: 'var(--admin-bg-card)',
            muted: 'var(--admin-bg-card-muted)',
            hover: 'var(--admin-bg-hover)',
            active: 'var(--admin-bg-active)',
          },
          text: {
            strong: 'var(--admin-text-strong)',
            base: 'var(--admin-text-base)',
            muted: 'var(--admin-text-muted)',
            soft: 'var(--admin-text-soft)',
            invert: 'var(--admin-text-on-primary)',
          },
          border: {
            subtle: 'var(--admin-border-subtle)',
            DEFAULT: 'var(--admin-border-default)',
            strong: 'var(--admin-border-strong)',
            focus: 'var(--admin-border-focus)',
          },
        },
        primary: {
          DEFAULT: 'var(--color-primary)',
          dark: 'var(--color-primary-dark)',
          darker: 'var(--color-primary-darker)',
          light: 'var(--color-primary-light)',
        },
        accent: {
          DEFAULT: 'var(--color-accent)',
          hover: 'var(--color-accent-hover)',
        },
        surface: 'var(--color-surface)',
        success: {
          DEFAULT: 'var(--color-success)',
          text: 'var(--color-success-text)',
          bg: 'var(--color-success-bg)',
        },
        warning: 'var(--color-warning)',
        error: {
          DEFAULT: 'var(--color-error)',
          text: 'var(--color-error-text)',
          bg: 'var(--color-error-bg)',
        },
        text: {
          DEFAULT: 'var(--color-text)',
          secondary: 'var(--color-text-secondary)',
        },
        bg: 'var(--color-bg)',
        white: 'var(--color-white)',
        gray: {
          50: 'var(--color-gray-50)',
          800: 'var(--color-gray-800)',
        },
      },
      fontFamily: {
        sans: ['var(--font-sans)'],
        serif: ['var(--font-serif)'],
        admin: ['var(--admin-font-family)'],
      },
      spacing: {
        1: 'var(--admin-space-1)',
        2: 'var(--admin-space-2)',
        3: 'var(--admin-space-3)',
        4: 'var(--admin-space-4)',
        5: 'var(--admin-space-5)',
        6: 'var(--admin-space-6)',
        8: 'var(--admin-space-8)',
        10: 'var(--admin-space-10)',
        12: 'var(--admin-space-12)',
        16: 'var(--admin-space-16)',
      },
      borderRadius: {
        xs: 'var(--admin-radius-xs)',
        sm: 'var(--admin-radius-sm)',
        md: 'var(--admin-radius-md)',
        lg: 'var(--admin-radius-lg)',
        xl: 'var(--admin-radius-xl)',
        pill: 'var(--admin-radius-pill)',
      },
      boxShadow: {
        'admin-xs': 'var(--admin-shadow-xs)',
        'admin-sm': 'var(--admin-shadow-sm)',
        'admin-md': 'var(--admin-shadow-md)',
        'admin-lg': 'var(--admin-shadow-lg)',
        'admin-focus': 'var(--admin-shadow-focus)',
      },
      fontSize: {
        'admin-xs': ['var(--admin-font-size-xs)', { lineHeight: 'var(--admin-line-height-normal)' }],
        'admin-sm': ['var(--admin-font-size-sm)', { lineHeight: 'var(--admin-line-height-normal)' }],
        'admin-md': ['var(--admin-font-size-md)', { lineHeight: 'var(--admin-line-height-relaxed)' }],
        'admin-lg': ['var(--admin-font-size-lg)', { lineHeight: 'var(--admin-line-height-relaxed)' }],
        'admin-xl': ['var(--admin-font-size-xl)', { lineHeight: 'var(--admin-line-height-tight)' }],
        'admin-2xl': ['var(--admin-font-size-2xl)', { lineHeight: 'var(--admin-line-height-tight)' }],
      },
      transitionDuration: {
        fast: 'var(--admin-duration-fast)',
        normal: 'var(--admin-duration-normal)',
        slow: 'var(--admin-duration-slow)',
      },
      maxWidth: {
        'admin-content': 'var(--admin-content-max)',
      },
      width: {
        'admin-sidebar': 'var(--admin-sidebar-width)',
        'admin-sidebar-collapsed': 'var(--admin-sidebar-width-collapsed)',
      },
      height: {
        'admin-header': 'var(--admin-header-height)',
      },
      zIndex: {
        sidebar: 'var(--admin-z-sidebar)',
        header: 'var(--admin-z-header)',
        dropdown: 'var(--admin-z-dropdown)',
        modal: 'var(--admin-z-modal)',
        toast: 'var(--admin-z-toast)',
      },
    },
  },
  plugins: [],
};

export default config;
