export const dashboardCopy = {
  en: {
    title: "Admin Health / QA Dashboard",
    subtitle:
      "Operational control surface for system health, pipeline flow, watchlist items, and live activity.",
    overviewReadyTitle: "Operational snapshot pending",
    overviewReadyBody: "Refresh to load the latest health status, watchlist totals, and operator cues.",
    overviewEmptyTitle: "No summary data in this snapshot",
    overviewEmptyBody: "The dashboard responded, but this snapshot did not include overview data to display.",
    loginTitle: "Admin sign in",
    loginSubtitle: "Use the same credentials as /api/v1/auth/login.",
    sessionActive: "Signed in session",
    sessionAs: "Signed in as",
    sessionUnknown: "Signed in (email unavailable)",
    email: "Admin email",
    password: "Password",
    signIn: "Sign in",
    signingIn: "Signing in",
    signOut: "Sign out",
    refresh: "Refresh dashboard",
    loading: "Loading dashboard",
    retry: "Retry",
    authRequired: "Sign in to load admin dashboard data.",
    idleState: "Dashboard is ready. Click refresh to load the latest summary.",
    loginMissing: "Email and password are required.",
    loginInvalid: "Invalid credentials.",
    loginError: "Unable to sign in right now.",
    loadError: "Unable to load dashboard summary right now.",
    loadErrorHint: "Check API health/auth configuration, then retry.",
    emptyState: "No dashboard data found yet.",
    emptyStateHint: "Check data pipelines and retry.",
    emptyWidgets: "No widgets found. Check backend summary contract.",
    widgets: "System health / QA overview",
    widgetsHint: "Primary checks across content, media, translations, and deploy readiness.",
    widgetsEmptyTitle: "No health widgets in this snapshot",
    widgetsEmptyBody: "This response completed successfully, but it did not include health widgets.",
    trendTitle: "Activity metrics",
    trendHint: "Lead activity trend backed by backend-provided daily inquiry buckets.",
    trendEmptyTitle: "No activity captured in this period",
    trendEmptyBody: "This time window does not contain lead activity yet. Try another period or wait for new submissions.",
    trendPeriod7d: "7D",
    trendPeriod30d: "30D",
    insightsTitle: "Pipeline summary",
    insightsHint: "Freshness timestamps and upstream hand-off signals from summary sources.",
    insightsEmptyTitle: "No freshness timestamps yet",
    insightsEmptyBody: "Upstream sources have not reported timestamp data for this snapshot yet.",
    generatedAt: "Generated at",
    incomplete: "Incomplete widgets",
    sectionReadyTitle: "Live data pending",
    sectionReadyBody: "Refresh this surface to load its latest status, timestamps, and quick actions.",
    sectionErrorTitle: "Section unavailable",
    recentInquiries: "Recent leads/inquiries",
    recentInquiriesHint: "Latest captured leads and inquiries from public entry points.",
    recentInquiriesEmptyTitle: "No recent inquiries in the current snapshot",
    recentInquiriesEmptyBody: "This snapshot does not include recent lead rows yet. New submissions will appear here automatically.",
    emptyInquiries: "No recent inquiries found.",
    sourcePage: "Source page",
    status: "Status",
    rows: "Rows",
    intent: "Intent",
    contact: "Contact",
    name: "Name",
    createdAt: "Created at",
    warnings: "Warnings",
    warningsHint: "Operator watchlist emitted by the summary endpoint.",
    warningsEmptyTitle: "No warnings reported",
    warningsEmptyBody: "The current snapshot did not report any warning conditions.",
    checkedAt: "Checked at",
    age: "Age",
    unknownValue: "Unknown",
    controlCenterTitle: "Control center",
    controlCenterHint: "Authentication, refresh actions, and direct operator controls.",
    watchlistTitle: "Watchlist",
    watchlistHint: "Warnings that need operator review before they turn into regressions.",
    logsTitle: "Logs",
    logsHint: "Recent inbound activity and lead capture logs.",
    backgroundTasksTitle: "Background tasks",
    backgroundTasksHint: "Import, mirror, and deploy jobs with their latest task outcomes.",
    backgroundTasksEmptyTitle: "No task summaries reported",
    backgroundTasksEmptyBody: "The latest snapshot did not include import, mirror, or deploy task summaries.",
    snapshot: "Snapshot",
    stable: "Stable",
    needsReview: "Needs review",
    liveInbox: "Live inbox",
    operatorQueue: "Operator queue",
    openCrm: "Open CRM",
    reviewWatchlist: "Review",
    taskImport: "Import sync",
    taskMirror: "Mirror refresh",
    taskDeploy: "Deploy health",
    openImports: "Open imports",
    openMedia: "Open media",
    openSeo: "Open SEO",
    latestTask: "Latest task",
    taskHealthy: "Healthy",
    taskAttention: "Needs attention",
    taskUnknown: "Unknown",
    taskError: "Error",
    taskSource: "Source",
    taskBuild: "Build",
    lastUpdated: "Last updated",
    metricValue: "Metric value",
    quickActions: "Quick actions",
    refreshRequired: "Refresh required",
    noSnapshotYet: "No snapshot yet",
    warningStatus: "Warning",
    errorStatus: "Error",
    workspaceLockedTitle: "Sign in required",
    workspaceLockedBody: "This dashboard keeps its structure visible, but live data loads only after admin sign-in.",
    overviewLockedBody: "Sign in to reveal live health status, freshness snapshots, and operator controls.",
    widgetsLockedBody: "Unlock content, media, translation, and deploy readiness checks for this workspace.",
    insightsLockedBody: "Reveal upstream timestamps and hand-off signals from the latest summary sources.",
    trendLockedBody: "Reveal daily lead activity and compare recent movement across time windows.",
    watchlistLockedBody: "Reveal warnings that need operator attention before they become production issues.",
    logsLockedBody: "Reveal the latest captured leads and inbound activity records.",
    tasksLockedBody: "Reveal import, mirror, and deploy job outcomes with their latest statuses.",
  },
  th: {
    title: "แดชบอร์ดสุขภาพระบบและ QA",
    subtitle: "ศูนย์ควบคุมสุขภาพระบบ ภาพรวมคิวงาน รายการเฝ้าระวัง และกิจกรรมล่าสุดของทีมแอดมิน",
    overviewReadyTitle: "รอโหลดภาพรวมการปฏิบัติการ",
    overviewReadyBody: "กดรีเฟรชเพื่อโหลดสถานะล่าสุด รายการเฝ้าระวัง และสัญญาณที่ทีมงานต้องติดตาม",
    overviewEmptyTitle: "สแนปช็อตนี้ยังไม่มีข้อมูลภาพรวม",
    overviewEmptyBody: "ระบบตอบกลับแล้ว แต่สแนปช็อตรอบนี้ยังไม่ส่งข้อมูลภาพรวมที่พร้อมแสดงผล",
    loginTitle: "เข้าสู่ระบบแอดมิน",
    loginSubtitle: "ใช้บัญชีเดียวกับ /api/v1/auth/login",
    sessionActive: "เซสชันที่เข้าสู่ระบบอยู่",
    sessionAs: "เข้าสู่ระบบเป็น",
    sessionUnknown: "เข้าสู่ระบบแล้ว (ไม่พบอีเมล)",
    email: "อีเมลแอดมิน",
    password: "รหัสผ่าน",
    signIn: "เข้าสู่ระบบ",
    signingIn: "กำลังเข้าสู่ระบบ",
    signOut: "ออกจากระบบ",
    refresh: "รีเฟรชแดชบอร์ด",
    loading: "กำลังโหลดแดชบอร์ด",
    retry: "ลองใหม่",
    authRequired: "กรุณาเข้าสู่ระบบก่อนใช้งานแดชบอร์ด",
    idleState: "แดชบอร์ดพร้อมใช้งานแล้ว กดรีเฟรชเพื่อโหลดข้อมูลล่าสุด",
    loginMissing: "ต้องกรอกอีเมลและรหัสผ่าน",
    loginInvalid: "ข้อมูลเข้าสู่ระบบไม่ถูกต้อง",
    loginError: "ไม่สามารถเข้าสู่ระบบได้ในขณะนี้",
    loadError: "ไม่สามารถโหลดสรุปแดชบอร์ดได้",
    loadErrorHint: "ตรวจสอบสถานะ API และการยืนยันตัวตน แล้วลองใหม่อีกครั้ง",
    emptyState: "ยังไม่พบข้อมูลสรุปแดชบอร์ด",
    emptyStateHint: "ตรวจสอบท่อข้อมูลและลองใหม่อีกครั้ง",
    emptyWidgets: "ยังไม่พบวิดเจ็ต โปรดตรวจสอบสัญญาสรุปข้อมูลจากระบบ",
    widgets: "ภาพรวมสุขภาพระบบ",
    widgetsHint: "ตรวจสอบคอนเทนต์ สื่อ คำแปล และความพร้อมก่อนดีพลอยในมุมมองเดียว",
    widgetsEmptyTitle: "สแนปช็อตนี้ยังไม่มีวิดเจ็ตสุขภาพระบบ",
    widgetsEmptyBody: "การตอบกลับรอบนี้สำเร็จ แต่ยังไม่ส่งวิดเจ็ตสุขภาพระบบเข้ามา",
    trendTitle: "แนวโน้มกิจกรรมของลีด",
    trendHint: "จำนวนลีดรายวันจากชุดข้อมูลกิจกรรมที่ระบบส่งมา",
    trendEmptyTitle: "ช่วงเวลานี้ยังไม่พบกิจกรรม",
    trendEmptyBody: "สแนปช็อตช่วงเวลานี้ยังไม่มีข้อมูลกิจกรรมของลีด ลองสลับช่วงเวลาหรือรอข้อมูลใหม่",
    trendPeriod7d: "7D",
    trendPeriod30d: "30D",
    insightsTitle: "สรุปคิวงาน",
    insightsHint: "เวลาอัปเดตล่าสุดและสัญญาณส่งต่องานจากระบบต้นทาง",
    insightsEmptyTitle: "สแนปช็อตนี้ยังไม่มีเวลาอัปเดตจากระบบต้นทาง",
    insightsEmptyBody: "เมื่อระบบต้นทางส่ง timestamp เข้ามา ส่วนนี้จะเริ่มแสดงผลทันที",
    generatedAt: "เวลาสร้างสแนปช็อต",
    incomplete: "วิดเจ็ตที่ยังไม่ครบ",
    sectionReadyTitle: "ข้อมูลล่าสุดกำลังรอโหลด",
    sectionReadyBody: "กดรีเฟรชเพื่อโหลดสถานะล่าสุด เวลาอัปเดต และปุ่มลัดของส่วนนี้",
    sectionErrorTitle: "ส่วนนี้ใช้งานไม่ได้",
    recentInquiries: "ลีดและอินไควรีล่าสุด",
    recentInquiriesHint: "รายการล่าสุดจากแบบฟอร์มและจุดรับลีดบนหน้าเว็บ",
    recentInquiriesEmptyTitle: "สแนปช็อตนี้ยังไม่มีอินไควรีล่าสุด",
    recentInquiriesEmptyBody: "รอบข้อมูลนี้ยังไม่พบแถวลีดล่าสุด เมื่อมีการส่งฟอร์มใหม่ รายการจะปรากฏตรงนี้",
    emptyInquiries: "ยังไม่พบอินไควรีล่าสุด",
    sourcePage: "หน้าต้นทาง",
    status: "สถานะ",
    rows: "แถว",
    intent: "เป้าหมาย",
    contact: "ช่องทางติดต่อ",
    name: "ชื่อ",
    createdAt: "เวลาสร้าง",
    warnings: "คำเตือน",
    warningsHint: "รายการเฝ้าระวังจาก summary endpoint ที่ผู้ดูแลควรตรวจสอบ",
    warningsEmptyTitle: "รอบนี้ไม่มีคำเตือนที่ระบบรายงาน",
    warningsEmptyBody: "สแนปช็อตปัจจุบันไม่พบคำเตือนที่ต้องติดตามต่อ",
    checkedAt: "เวลาตรวจ",
    age: "อายุข้อมูล",
    unknownValue: "ไม่ทราบ",
    controlCenterTitle: "ศูนย์ควบคุม",
    controlCenterHint: "จัดการการเข้าสู่ระบบ การรีเฟรช และคำสั่งหลักของผู้ดูแล",
    watchlistTitle: "รายการเฝ้าระวัง",
    watchlistHint: "ประเด็นที่ควรตรวจสอบก่อนลุกลามเป็นปัญหา",
    logsTitle: "บันทึกเหตุการณ์",
    logsHint: "กิจกรรมลีดเข้าและบันทึกการรับข้อมูลล่าสุด",
    backgroundTasksTitle: "งานเบื้องหลัง",
    backgroundTasksHint: "งานนำเข้า มิเรอร์ และดีพลอย พร้อมผลลัพธ์ล่าสุด",
    backgroundTasksEmptyTitle: "สแนปช็อตนี้ยังไม่มีสรุปงานเบื้องหลัง",
    backgroundTasksEmptyBody: "รอบข้อมูลล่าสุดยังไม่ส่งสรุปงานนำเข้า มิเรอร์ หรือดีพลอยเข้ามา",
    snapshot: "สแนปช็อต",
    stable: "เสถียร",
    needsReview: "ต้องตรวจ",
    liveInbox: "กล่องเข้าแบบสด",
    operatorQueue: "คิวผู้ดูแล",
    openCrm: "เปิด CRM",
    reviewWatchlist: "ตรวจสอบ",
    taskImport: "สถานะนำเข้า",
    taskMirror: "สถานะมิเรอร์",
    taskDeploy: "สถานะดีพลอย",
    openImports: "ดูงานนำเข้า",
    openMedia: "ดูคลังสื่อ",
    openSeo: "ดู SEO",
    latestTask: "งานล่าสุด",
    taskHealthy: "ปกติ",
    taskAttention: "ต้องตรวจ",
    taskUnknown: "ไม่ทราบ",
    taskError: "ผิดพลาด",
    taskSource: "ต้นทาง",
    taskBuild: "บิลด์",
    lastUpdated: "อัปเดตล่าสุด",
    metricValue: "ค่าตัวชี้วัด",
    quickActions: "การดำเนินการด่วน",
    refreshRequired: "ต้องรีเฟรช",
    noSnapshotYet: "ยังไม่มีสแนปช็อต",
    warningStatus: "เตือน",
    errorStatus: "ผิดพลาด",
    workspaceLockedTitle: "ต้องเข้าสู่ระบบก่อน",
    workspaceLockedBody: "โครงสร้างแดชบอร์ดยังแสดงให้ตรวจสอบได้ แต่ข้อมูลจริงจะโหลดหลังจากผู้ดูแลเข้าสู่ระบบแล้วเท่านั้น",
    overviewLockedBody: "เข้าสู่ระบบเพื่อดูสถานะสุขภาพล่าสุด สแนปช็อตเวลาอัปเดต และเครื่องมือควบคุมของผู้ดูแล",
    widgetsLockedBody: "ปลดล็อกมุมมองคอนเทนต์ สื่อ คำแปล และความพร้อมก่อนดีพลอยของ workspace นี้",
    insightsLockedBody: "ปลดล็อกเวลาอัปเดตและสัญญาณส่งต่องานจากแหล่งข้อมูลล่าสุด",
    trendLockedBody: "ปลดล็อกแนวโน้มลีดรายวันและเปรียบเทียบความเคลื่อนไหวตามช่วงเวลา",
    watchlistLockedBody: "ปลดล็อกรายการที่ผู้ดูแลต้องติดตามก่อนลุกลามเป็นปัญหาในการใช้งานจริง",
    logsLockedBody: "ปลดล็อกบันทึกลีดและกิจกรรมรับข้อมูลล่าสุดของระบบ",
    tasksLockedBody: "ปลดล็อกผลลัพธ์ล่าสุดของงานนำเข้า มิเรอร์ และดีพลอย",
  },
} as const;
