export const dashboardCopy = {
  en: {
    title: "Admin Health / QA Dashboard",
    subtitle:
      "Operational control surface for system health, pipeline flow, watchlist items, and live activity.",
    overviewReadyTitle: "Ready to load overview",
    overviewReadyBody: "Refresh the dashboard to load the latest QA snapshot.",
    overviewEmptyTitle: "Overview unavailable",
    overviewEmptyBody: "Dashboard summary responded without any visible content yet.",
    loginTitle: "Admin sign in",
    loginSubtitle: "Use the same credentials as /api/v1/auth/login.",
    sessionActive: "Signed in session",
    sessionAs: "Signed in as",
    sessionUnknown: "Signed in (email unavailable)",
    email: "Admin email",
    password: "Password",
    signIn: "Sign in",
    signingIn: "Signing in",
    signOut: "Sign out",
    refresh: "Refresh dashboard",
    loading: "Loading dashboard",
    retry: "Retry",
    authRequired: "Sign in to load admin dashboard data.",
    idleState: "Dashboard is ready. Click refresh to load the latest summary.",
    loginMissing: "Email and password are required.",
    loginInvalid: "Invalid credentials.",
    loginError: "Unable to sign in right now.",
    loadError: "Unable to load dashboard summary right now.",
    loadErrorHint: "Check API health/auth configuration, then retry.",
    emptyState: "No dashboard data found yet.",
    emptyStateHint: "Check data pipelines and retry.",
    emptyWidgets: "No widgets found. Check backend summary contract.",
    widgets: "System health / QA overview",
    widgetsHint: "Primary checks across content, media, translations, and deploy readiness.",
    widgetsEmptyTitle: "No widgets returned",
    widgetsEmptyBody: "Backend summary returned no health widgets for this snapshot.",
    trendTitle: "Activity metrics",
    trendHint: "Lead activity trend backed by backend-provided daily inquiry buckets.",
    trendEmptyTitle: "No activity in this window",
    trendEmptyBody: "Switch periods or wait for new inquiry activity to appear in this trend.",
    trendPeriod7d: "7D",
    trendPeriod30d: "30D",
    insightsTitle: "Pipeline summary",
    insightsHint: "Freshness timestamps and upstream hand-off signals from summary sources.",
    insightsEmptyTitle: "No freshness insights",
    insightsEmptyBody: "Freshness signals will appear here when upstream jobs report timestamps.",
    generatedAt: "Generated at",
    incomplete: "Incomplete widgets",
    sectionReadyTitle: "Ready to load",
    sectionReadyBody: "Refresh the dashboard to populate this section.",
    sectionErrorTitle: "Section unavailable",
    recentInquiries: "Recent leads/inquiries",
    recentInquiriesHint: "Latest captured leads and inquiries from public entry points.",
    recentInquiriesEmptyTitle: "No recent inquiries",
    recentInquiriesEmptyBody: "New lead rows will appear here after the next captured submission.",
    emptyInquiries: "No recent inquiries found.",
    sourcePage: "Source page",
    status: "Status",
    rows: "Rows",
    intent: "Intent",
    contact: "Contact",
    name: "Name",
    createdAt: "Created at",
    warnings: "Warnings",
    warningsHint: "Operator watchlist emitted by the summary endpoint.",
    warningsEmptyTitle: "No active warnings",
    warningsEmptyBody: "Current snapshot has no warning messages.",
    checkedAt: "Checked at",
    age: "Age",
    unknownValue: "Unknown",
    controlCenterTitle: "Control center",
    controlCenterHint: "Authentication, refresh actions, and direct operator controls.",
    watchlistTitle: "Watchlist",
    watchlistHint: "Warnings that need operator review before they turn into regressions.",
    logsTitle: "Logs",
    logsHint: "Recent inbound activity and lead capture logs.",
    backgroundTasksTitle: "Background tasks",
    backgroundTasksHint: "Import, mirror, and deploy jobs with their latest task outcomes.",
    backgroundTasksEmptyTitle: "No background tasks",
    backgroundTasksEmptyBody: "Task summaries will appear after the next system run.",
    snapshot: "Snapshot",
    stable: "Stable",
    needsReview: "Needs review",
    liveInbox: "Live inbox",
    operatorQueue: "Operator queue",
    openCrm: "Open CRM",
    reviewWatchlist: "Review",
    taskImport: "Import sync",
    taskMirror: "Mirror refresh",
    taskDeploy: "Deploy health",
    openImports: "Open imports",
    openMedia: "Open media",
    openSeo: "Open SEO",
    latestTask: "Latest task",
    taskHealthy: "Healthy",
    taskAttention: "Needs attention",
    taskUnknown: "Unknown",
    taskSource: "Source",
    taskBuild: "Build",
    workspaceLockedTitle: "Sign in required",
    workspaceLockedBody: "This dashboard keeps its structure visible, but live data loads only after admin sign-in.",
  },
  th: {
    title: "Admin Health / QA Dashboard",
    subtitle: "ศูนย์ควบคุมสำหรับสุขภาพระบบ pipeline watchlist และ activity ล่าสุดของแอดมิน",
    overviewReadyTitle: "พร้อมโหลดภาพรวม",
    overviewReadyBody: "กดรีเฟรชเพื่อโหลด snapshot ล่าสุดของแดชบอร์ด",
    overviewEmptyTitle: "ยังไม่มีภาพรวม",
    overviewEmptyBody: "summary ตอบกลับมา แต่ยังไม่มีข้อมูลที่แสดงผลได้",
    loginTitle: "เข้าสู่ระบบแอดมิน",
    loginSubtitle: "ใช้บัญชีเดียวกับ /api/v1/auth/login",
    sessionActive: "เซสชันที่เข้าสู่ระบบอยู่",
    sessionAs: "เข้าสู่ระบบเป็น",
    sessionUnknown: "เข้าสู่ระบบแล้ว (ไม่พบอีเมล)",
    email: "อีเมลแอดมิน",
    password: "รหัสผ่าน",
    signIn: "เข้าสู่ระบบ",
    signingIn: "กำลังเข้าสู่ระบบ",
    signOut: "ออกจากระบบ",
    refresh: "รีเฟรชแดชบอร์ด",
    loading: "กำลังโหลดแดชบอร์ด",
    retry: "ลองใหม่",
    authRequired: "กรุณาเข้าสู่ระบบก่อนใช้งานแดชบอร์ด",
    idleState: "พร้อมใช้งานแดชบอร์ดแล้ว กดรีเฟรชเพื่อโหลดข้อมูลล่าสุด",
    loginMissing: "ต้องกรอกอีเมลและรหัสผ่าน",
    loginInvalid: "ข้อมูลเข้าสู่ระบบไม่ถูกต้อง",
    loginError: "ไม่สามารถเข้าสู่ระบบได้ในขณะนี้",
    loadError: "ไม่สามารถโหลดสรุปแดชบอร์ดได้",
    loadErrorHint: "ตรวจสอบ API/auth แล้วลองใหม่",
    emptyState: "ยังไม่พบข้อมูลสรุปแดชบอร์ด",
    emptyStateHint: "ตรวจ pipeline ข้อมูลแล้วลองใหม่อีกครั้ง",
    emptyWidgets: "ยังไม่พบวิดเจ็ต ตรวจสอบ backend summary contract",
    widgets: "System health / QA overview",
    widgetsHint: "เช็กหลักของ content, media, translations และความพร้อมของ deploy",
    widgetsEmptyTitle: "ยังไม่มีวิดเจ็ต",
    widgetsEmptyBody: "backend summary ยังไม่ส่ง health widget มาในรอบนี้",
    trendTitle: "Activity metrics",
    trendHint: "แนวโน้ม activity ของลีดจาก daily inquiry buckets ของ backend",
    trendEmptyTitle: "ช่วงเวลานี้ยังไม่มี activity",
    trendEmptyBody: "ลองสลับช่วงเวลา หรือรอ activity ใหม่เข้ามาในกราฟนี้",
    trendPeriod7d: "7D",
    trendPeriod30d: "30D",
    insightsTitle: "Pipeline summary",
    insightsHint: "สรุป freshness timestamp และสัญญาณ hand-off จาก upstream jobs",
    insightsEmptyTitle: "ยังไม่มี freshness insight",
    insightsEmptyBody: "เมื่อ upstream jobs ส่ง timestamp เข้ามา จะเริ่มแสดงผลในส่วนนี้",
    generatedAt: "เวลาสร้าง snapshot",
    incomplete: "วิดเจ็ตที่ยังไม่ครบ",
    sectionReadyTitle: "พร้อมโหลด",
    sectionReadyBody: "กดรีเฟรชเพื่อเติมข้อมูลในส่วนนี้",
    sectionErrorTitle: "ส่วนนี้ใช้งานไม่ได้",
    recentInquiries: "ลีด / inquiry ล่าสุด",
    recentInquiriesHint: "รายการลีดล่าสุดที่เข้ามาจาก entry points หน้า public",
    recentInquiriesEmptyTitle: "ยังไม่มี inquiry ล่าสุด",
    recentInquiriesEmptyBody: "เมื่อมีการส่งลีดครั้งถัดไป ตารางนี้จะเริ่มแสดงข้อมูล",
    emptyInquiries: "ยังไม่พบ inquiry ล่าสุด",
    sourcePage: "หน้าต้นทาง",
    status: "สถานะ",
    rows: "แถว",
    intent: "เป้าหมาย",
    contact: "ช่องทางติดต่อ",
    name: "ชื่อ",
    createdAt: "เวลาสร้าง",
    warnings: "คำเตือน",
    warningsHint: "watchlist ที่ summary endpoint แจ้งให้ operator ตรวจสอบ",
    warningsEmptyTitle: "ไม่มีคำเตือนค้างอยู่",
    warningsEmptyBody: "snapshot ปัจจุบันไม่มีข้อความเตือนที่ต้องติดตาม",
    checkedAt: "เวลาตรวจ",
    age: "อายุข้อมูล",
    unknownValue: "ไม่ทราบ",
    controlCenterTitle: "Control center",
    controlCenterHint: "ล็อกอิน รีเฟรช และ action หลักของ operator",
    watchlistTitle: "Watchlist",
    watchlistHint: "รายการเตือนที่ควรตรวจสอบก่อนกลายเป็น regression",
    logsTitle: "Logs",
    logsHint: "activity ล่าสุดของ inbound leads และการเก็บข้อมูลฟอร์ม",
    backgroundTasksTitle: "Background tasks",
    backgroundTasksHint: "งาน import, mirror และ deploy พร้อมผลลัพธ์ล่าสุด",
    backgroundTasksEmptyTitle: "ยังไม่มี background tasks",
    backgroundTasksEmptyBody: "หลังระบบรันรอบถัดไป จะเริ่มมี task summary ในส่วนนี้",
    snapshot: "Snapshot",
    stable: "เสถียร",
    needsReview: "ต้องตรวจ",
    liveInbox: "กล่องเข้า live",
    operatorQueue: "คิว operator",
    openCrm: "เปิด CRM",
    reviewWatchlist: "ตรวจสอบ",
    taskImport: "Import sync",
    taskMirror: "Mirror refresh",
    taskDeploy: "Deploy health",
    openImports: "เปิด Imports",
    openMedia: "เปิด Media",
    openSeo: "เปิด SEO",
    latestTask: "งานล่าสุด",
    taskHealthy: "ปกติ",
    taskAttention: "ต้องตรวจ",
    taskUnknown: "ไม่ทราบ",
    taskSource: "Source",
    taskBuild: "Build",
    workspaceLockedTitle: "ต้องเข้าสู่ระบบก่อน",
    workspaceLockedBody: "โครงสร้างแดชบอร์ดยังแสดงได้ แต่ข้อมูลจริงจะโหลดหลังจากแอดมินล็อกอินเท่านั้น",
  },
} as const;
