import type { AdminLocale } from "@/app/_lib/admin-i18n";
import type { CrudConfig } from "@/components/admin/domain/crud-workspace/workspace-types";

type WorkspaceDisplayCopy = Partial<Pick<CrudConfig, "title" | "subtitle" | "identifierLabel" | "queryHelp">>;

const ROUTE_COPY_BY_TITLE: Record<string, Partial<Record<AdminLocale, WorkspaceDisplayCopy>>> = {
  "Projects CMS": {
    th: {
      title: "จัดการโครงการ",
      subtitle: "จัดการข้อมูลโครงการผ่าน API เดิมของระบบ และใช้ประเภททรัพย์จากชุด taxonomy เดิม",
      identifierLabel: "รหัสโครงการ",
      queryHelp: "รองรับ: limit",
    },
  },
  "Properties CMS": {
    th: {
      title: "จัดการทรัพย์",
      subtitle: "จัดการรายการทรัพย์ผ่าน API เดิมของระบบ พร้อมตัวกรองค้นหา สถานะ และโครงการอ้างอิง",
      identifierLabel: "รหัสทรัพย์",
      queryHelp: "รองรับ: page, limit, search, status, type, project_id, area_id",
    },
  },
  "User & Role Management": {
    th: {
      title: "จัดการผู้ใช้และสิทธิ์",
      subtitle: "สร้างและปรับสิทธิ์ผู้ใช้ผ่านสัญญา API เดิม โดยใช้ role_ids สำหรับอัปเดตการกำหนดบทบาท",
      identifierLabel: "รหัสผู้ใช้",
      queryHelp: "ดึง role จาก /admin/roles แล้วส่ง role_ids เป็น JSON array เพื่อกำหนดหรือถอดสิทธิ์",
    },
  },
  "Areas CMS": {
    th: {
      title: "จัดการโซนและพื้นที่",
      subtitle: "ดูแลข้อมูลพื้นที่ เนื้อหา locale และสถานะ publish readiness ผ่าน API เดิม",
      identifierLabel: "รหัสพื้นที่",
      queryHelp: "รองรับ: limit และขั้นตอนเผยแพร่ Check readiness → Publish → Unpublish",
    },
  },
  "Developers CMS": {
    th: {
      title: "จัดการผู้พัฒนา",
      subtitle: "ดูแลข้อมูลผู้พัฒนา โปรไฟล์หลายภาษา และสถานะพร้อมเผยแพร่ผ่าน API เดิม",
      identifierLabel: "รหัสผู้พัฒนา",
      queryHelp: "รองรับ: limit และขั้นตอนเผยแพร่ Check readiness → Publish → Unpublish",
    },
  },
  "Company CMS": {
    th: {
      title: "จัดการข้อมูลบริษัท",
      subtitle: "ปรับข้อมูลหน้า company ผ่าน API เดิม พร้อมรองรับการอัปเดตเนื้อหาและเมตา",
      identifierLabel: "slug บริษัท",
    },
  },
  "Testimonials CMS": {
    th: {
      title: "จัดการรีวิวลูกค้า",
      subtitle: "จัดการรีวิวและคำรับรองผ่าน API เดิมของระบบ",
      identifierLabel: "รหัสรีวิว",
    },
  },
  "Blog CMS": {
    th: {
      title: "จัดการบทความ",
      subtitle: "จัดการบทความและไกด์ผ่าน API บทความเดิม พร้อม taxonomy และ revision history",
      identifierLabel: "slug บทความ",
      queryHelp: "รองรับ: category, status, page, limit",
    },
  },
  "Editorial Review Queue": {
    th: {
      title: "คิวรีวิวบทความ",
      subtitle: "ตรวจสอบและอนุมัติบทความที่อยู่ในสถานะ in_review ผ่าน workflow เดิม",
      identifierLabel: "slug บทความ",
      queryHelp: "รองรับ: status=in_review, page, limit",
    },
  },
  "Taxonomy CMS": {
    th: {
      title: "จัดการหมวดหมู่กลาง",
      subtitle: "ดูแล registry กลางของ tags, topics, facilities และ type ผ่าน API taxonomy เดิม",
      identifierLabel: "รหัส taxonomy",
      queryHelp: "รองรับ: kind, status, page, limit",
    },
  },
  "Videos CMS": {
    th: {
      title: "จัดการวิดีโอ",
      subtitle: "จัดการเนื้อหาวิดีโอผ่าน API เดิม พร้อมสถานะและรายละเอียดหลายภาษา",
      identifierLabel: "slug วิดีโอ",
      queryHelp: "รองรับ: status, page, limit",
    },
  },
};

const CRUD_WORKSPACE_COPY = {
  en: {
    eyebrow: "Admin workspace",
    createEnabled: "Create enabled",
    patchEnabled: "Patch enabled",
    sessionTitle: "Session",
    sessionDescription: "Active auth session for this workspace.",
    signInTitle: "Admin sign in",
    signInDescription: "Use existing admin credentials to access this workspace.",
    email: "Email",
    password: "Password",
    signingIn: "Signing in",
    signIn: "Sign in",
    signedInAs: "Signed in as",
    signedInFallback: "Signed in session active.",
    refreshList: "Refresh list",
    loading: "Loading",
    signOut: "Sign out",
    authEmptyTitle: "Sign in to manage this workspace.",
    authEmptyBody: "Use the existing admin session to unlock records, mutations, and revision tools.",
    listQueryTitle: "List query",
    listQueryDescription: "Use existing query params without changing API contracts.",
    listQueryLabel: "List query",
    loadList: "Load list",
    pageMetric: "page",
    limitMetric: "limit",
    totalMetric: "total",
    recordActionsTitle: "Record actions",
    recordActionsDescription: "Select one record ID and run safe read/write actions.",
    getDetail: "Get detail",
    checkReadiness: "Check readiness",
    publish: "Publish",
    unpublish: "Unpublish",
    delete: "Delete",
    loadRevisions: "Load revisions",
    createRecordTitle: "Create record",
    createRecordDescription: "Create a new record using the existing workspace contract.",
    createPayloadJson: "Create payload JSON",
    create: "Create",
    updateRecordTitle: "Update record",
    updateRecordDescription: "Patch the selected record without changing the API payload shape.",
    patchPayloadJson: "Patch payload JSON",
    patch: "Patch",
    bulkActionsTitle: "Bulk actions",
    bulkActionsDescription: "Run scoped batch updates without changing the existing API contract.",
    batchUpdate: "Batch update",
    recordsTitle: "Records",
    recordsDescription: "Current list results rendered through the shared admin data table.",
    recordsIdle: "Load the list to view records for this workspace.",
    recordsEmpty: "No records",
    use: "Use",
    useRecordHint: "Load this row into the action panels",
    activeRecord: "Active record",
    identifier: "Identifier",
    slug: "Slug",
    nameTitle: "Name/Title",
    statusUpdated: "Status/Updated",
    resultTitle: "Result",
    resultDescription: "Latest response payload from the selected workspace action.",
    revisionsTitle: "Revision history",
    revisionsDescription: "Inspect revisions, diff snapshots, and restore when the endpoint supports it.",
    revisionsEmpty: 'No revisions loaded. Select a record and click "Load revisions".',
    revision: "Revision",
    showDiff: "Show diff",
    restoreRevision: "Restore revision",
    previewTitle: "Preview",
    previewDescription: "Localized preview content and translation completeness for the current record.",
    translationCompleteness: "Translation completeness",
    translationCompletenessDescription: "Localized field coverage from the current publish checklist.",
    previewLocaleDescription: "Preview locale",
    missingCredentials: "Email and password are required.",
    invalidCredentials: "Invalid credentials.",
    unableSignIn: "Unable to sign in.",
    signInRequired: "Sign in is required.",
    loadFailed: "Unable to load data.",
    requestFailed: "Request failed.",
    fixFields: "Please correct the highlighted fields.",
  },
  th: {
    eyebrow: "พื้นที่ทำงานแอดมิน",
    createEnabled: "เปิดใช้งานการสร้างแล้ว",
    patchEnabled: "เปิดใช้งานการแก้ไขแล้ว",
    sessionTitle: "เซสชัน",
    sessionDescription: "เซสชันยืนยันตัวตนที่ใช้งานอยู่สำหรับพื้นที่ทำงานนี้",
    signInTitle: "เข้าสู่ระบบแอดมิน",
    signInDescription: "ใช้บัญชีแอดมินเดิมเพื่อเปิดใช้งานพื้นที่ทำงานนี้",
    email: "อีเมล",
    password: "รหัสผ่าน",
    signingIn: "กำลังเข้าสู่ระบบ",
    signIn: "เข้าสู่ระบบ",
    signedInAs: "เข้าสู่ระบบเป็น",
    signedInFallback: "มีเซสชันที่เข้าสู่ระบบอยู่",
    refreshList: "รีเฟรชรายการ",
    loading: "กำลังโหลด",
    signOut: "ออกจากระบบ",
    authEmptyTitle: "เข้าสู่ระบบก่อนจัดการพื้นที่ทำงานนี้",
    authEmptyBody: "เมื่อเข้าสู่ระบบแล้ว คุณจะเข้าถึงรายการข้อมูล การแก้ไข การเผยแพร่ และ revision tools ได้ทันที",
    listQueryTitle: "คิวรีรายการ",
    listQueryDescription: "ใช้พารามิเตอร์ query เดิมของระบบโดยไม่เปลี่ยนสัญญา API",
    listQueryLabel: "พารามิเตอร์รายการ",
    loadList: "โหลดรายการ",
    pageMetric: "หน้า",
    limitMetric: "จำนวนต่อหน้า",
    totalMetric: "ทั้งหมด",
    recordActionsTitle: "คำสั่งต่อรายการ",
    recordActionsDescription: "เลือกรหัสรายการหนึ่งรายการ แล้วสั่งอ่านหรือแก้ไขอย่างปลอดภัย",
    getDetail: "ดูรายละเอียด",
    checkReadiness: "ตรวจความพร้อม",
    publish: "เผยแพร่",
    unpublish: "ยกเลิกเผยแพร่",
    delete: "ลบ",
    loadRevisions: "โหลด revision",
    createRecordTitle: "สร้างรายการใหม่",
    createRecordDescription: "สร้างรายการใหม่ผ่านสัญญา workspace เดิมของระบบ",
    createPayloadJson: "JSON สำหรับสร้างรายการ",
    create: "สร้างรายการ",
    updateRecordTitle: "แก้ไขรายการ",
    updateRecordDescription: "อัปเดตรายการที่เลือกโดยไม่เปลี่ยนรูปแบบ payload ของ API",
    patchPayloadJson: "JSON สำหรับแก้ไขรายการ",
    patch: "บันทึกการแก้ไข",
    bulkActionsTitle: "คำสั่งแบบกลุ่ม",
    bulkActionsDescription: "สั่งอัปเดตหลายรายการพร้อมกันโดยยังใช้สัญญา API เดิม",
    batchUpdate: "อัปเดตหลายรายการ",
    recordsTitle: "รายการข้อมูล",
    recordsDescription: "ผลลัพธ์รายการล่าสุดที่แสดงผ่าน shared admin data table",
    recordsIdle: "กดโหลดรายการเพื่อดูข้อมูลของ workspace นี้",
    recordsEmpty: "ยังไม่พบรายการข้อมูล",
    use: "เลือกใช้",
    useRecordHint: "โหลดแถวนี้เข้าสู่แผงคำสั่งด้านข้าง",
    activeRecord: "ระเบียนที่ใช้งานอยู่",
    identifier: "รหัสอ้างอิง",
    slug: "Slug",
    nameTitle: "ชื่อ/หัวข้อ",
    statusUpdated: "สถานะ/เวลาอัปเดต",
    resultTitle: "ผลลัพธ์ล่าสุด",
    resultDescription: "ผลตอบกลับล่าสุดจากคำสั่งที่เรียกใช้งานใน workspace นี้",
    revisionsTitle: "ประวัติ revision",
    revisionsDescription: "ตรวจ revision, diff และการกู้คืนเมื่อ endpoint รองรับ",
    revisionsEmpty: 'ยังไม่ได้โหลด revision เลือกรายการก่อน แล้วกด "โหลด revision"',
    revision: "Revision",
    showDiff: "ดู diff",
    restoreRevision: "กู้คืน revision",
    previewTitle: "ตัวอย่างข้อมูล",
    previewDescription: "ดูตัวอย่างเนื้อหาหลายภาษาและความครบถ้วนของฟิลด์ก่อนเผยแพร่",
    translationCompleteness: "ความครบถ้วนของคำแปล",
    translationCompletenessDescription: "สัดส่วนฟิลด์หลายภาษาที่กรอกครบจาก publish checklist ปัจจุบัน",
    previewLocaleDescription: "ตัวอย่างตามภาษา",
    missingCredentials: "ต้องกรอกอีเมลและรหัสผ่าน",
    invalidCredentials: "ข้อมูลเข้าสู่ระบบไม่ถูกต้อง",
    unableSignIn: "ไม่สามารถเข้าสู่ระบบได้ในขณะนี้",
    signInRequired: "กรุณาเข้าสู่ระบบก่อน",
    loadFailed: "ไม่สามารถโหลดข้อมูลได้",
    requestFailed: "คำขอไม่สำเร็จ",
    fixFields: "กรุณาแก้ไขข้อมูลในช่องที่มีการแจ้งเตือน",
  },
} as const satisfies Record<AdminLocale, Record<string, string>>;

type CrudWorkspaceCopyKey = keyof (typeof CRUD_WORKSPACE_COPY)["en"];

export type CrudWorkspaceCopy = Record<CrudWorkspaceCopyKey, string>;

export function getCrudWorkspaceCopy(locale: AdminLocale): CrudWorkspaceCopy {
  return CRUD_WORKSPACE_COPY[locale] as CrudWorkspaceCopy;
}

export function getCrudWorkspaceDisplayConfig(config: CrudConfig, locale: AdminLocale) {
  const localized = ROUTE_COPY_BY_TITLE[config.title]?.[locale];
  return {
    title: localized?.title ?? config.title,
    subtitle: localized?.subtitle ?? config.subtitle,
    identifierLabel: localized?.identifierLabel ?? config.identifierLabel,
    queryHelp: localized?.queryHelp ?? config.queryHelp,
  };
}
