<?php
 include_once("config.php"); $conn = new mysqli($SERVER_NAME, $DB_USERNAME, $DB_PASSWORD, $DB_NAME); $conn->set_charset('utf8'); $table = @mysqli_real_escape_string($conn, $_GET["table"]); $column = @mysqli_real_escape_string($conn, $_GET["column"]); loadConfig(); ?><div class="card card-success"><div class="card-header"><h4 class="card-title">
      Editing <span style='color:yellow'><?php echo $table." / ".$column?></span> parameters
    </h4></div><div class="card-body"><?php
 $kEl = array_keys($db[$table][$column]); for($el=0; $el < count($kEl); $el++) { ?><div class='row'><div class='col-md-6'><?php echo $kEl[$el]?></div><div class='col-md-6'><?php
 $k = $kEl[$el]; $v = $db[$table][$column][$k]; if ($k == 'Mandatory') { echo "<select class='form-control'><option ".($v=='Yes'?"selected":"").">Yes</option><option ".($v=='No'?"selected":"").">No</option></select>"; } else if ($k == 'Syntax Check') { echo "<select name='Syntax Check' class='form-control'><option ".($v=='Client'?"selected":"").">Client</option><option ".($v=='Server'?"selected":"").">Server</option></select>"; } else if ($k == 'Lookup Field') { ?><select name='Lookup Field' class='form-control'><option></option><?php
 $colKeys = array_keys($db[$table]); for($i=0; $i<count($db[$table]); $i++) { $newValue = $colKeys[$i]; if ($column == $newValue) continue; $selected = ''; if ($newValue == $v) $selected = 'selected'; echo "<option $selected>{$colKeys[$i]}</option>"; } ?></select><?php
 } else if ($k == 'Edit Mode') { ?><select name='Edit Mode' class='form-control'><option <?php echo $v==''?'selected':''?>></option><option <?php echo $v=='textarea'?'selected':''?>>textarea</option><option <?php echo $v=='html'?'selected':''?>>html</option><option <?php echo $v=='upload'?'selected':''?>>upload</option></select><?php
 } else if ($k == 'View Mode') { ?><select name='View Mode' class='form-control'><option <?php echo $v==''?'selected':''?>></option><option <?php echo $v=='fullText'?'selected':''?>>fullText</option><option <?php echo $v=='img'?'selected':''?>>img</option><option <?php echo $v=='img-xs'?'selected':''?>>img-xs</option><option <?php echo $v=='img-s'?'selected':''?>>img-s</option><option <?php echo $v=='img-m'?'selected':''?>>img-m</option><option <?php echo $v=='img-l'?'selected':''?>>img-l</option></select><?php
 } else if ($k == 'Status') { ?><select name='Status' class='form-control'><option <?php echo $v=='Writeable'?'selected':''?>>Writeable</option><option <?php echo $v=='Read Only'?'selected':''?>>Read Only</option><option <?php echo $v=='Hidden'?'selected':''?>>Hidden</option></select><?php
 } else if ($k == 'MySQL Type') { echo "<input disabled class='form-control' type=text name='<?php echo $k?>' value='$v'>"; } else echo "<input class='form-control' type=text name='<?php echo $k?>' value='$v'>"; ?></div></div><?php
 } ?><input type=submit value='Save' class='btn btn-primary'></div></div>
